Installation de oh-my-zsh
Utilisation du [script
d'installation](https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)

diff --git a/img-ide/Dockerfile b/img-ide/Dockerfile
--- a/img-ide/Dockerfile
+++ b/img-ide/Dockerfile
@@ -16,28 +16,6 @@ USER eclim
 WORKDIR /home/eclim
 
 # installation de oh-my-zsh
-ENV ZSH $HOME/.oh-my-zsh
-RUN git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git | sh
-
-# installation de conscript
-RUN curl https://raw.githubusercontent.com/n8han/conscript/master/setup.sh | sh
-RUN PATH=$PATH:$HOME/bin/cs
-
-RUN $HOME/sbt_test.sh && \
-	rm -rf build.sbt target project sbt_test.sh
-
-# installation de giter8
-RUN $HOME/bin/cs n8han/giter8
-RUN $HOME/bin/g8 n8han/giter8 --name=test && \
-	rm -rf $HOME/test # le projet est initialisé pour télécharger les dépendances de giter8
-
-# installtion de neobundle pour vim
-RUN curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
-# téléchargement de mon .vimrc
-RUN curl https://raw.githubusercontent.com/elongeau/dotfiles/master/.vimrc > .vimrc
-RUN $HOME/.vim/bundle/neobundle.vim/bin/neoinstall
-
-# création d'un répertoire pour les backup des fichiers édités dans vim
-RUN mkdir $HOME/.vim-tmp
+RUN curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh || echo "Don't care of errors"
 
 CMD zsh
